#app.yaml
runtime: python39

env_variables:
  CLOUD_SQL_USERNAME: sonali
  CLOUD_SQL_PASSWORD: 123456789
  CLOUD_SQL_DATABASE_NAME: menu
  CLOUD_SQL_CONNECTION_NAME: chatbot-wsrv:asia-south2:menu-details